services:
  - type: web
    name: frameworkorpokemon
    runtime: docker # <-- Change from 'node' to 'docker'
    # Remove 'buildCommand' and 'startCommand' lines if they are present, 
    # as Docker handle these inside the image.
